name: Build Herpaderping
 
on: [push]
 
jobs:
  build:
 
    runs-on: windows-latest
 
    steps:
    - uses: actions/checkout@v2
      name: Checkout Code
      with:
       submodules: 'recursive'
            
    - name: Setup MSBuild Path
      uses:  warrenbuckley/Setup-MSBuild@v1
       
    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1.0.2

    - name: Restore NuGet Packages
      run: nuget restore herpaderping.sln 
 
    - name: Build App
      run: msbuild herpaderping.sln /p:Configuration=Release /p:DeployOnBuild=true /p:PublishProfile=FolderProfile
 
    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: herpaderping
        path: "D:/a/herpaderping/herpaderping/Inveigh/obj/Debug/"
